

name: s3server CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Compile with Maven
      run: mvn compile
    - name: Test with Maven
      run: mvn test
    - name: Package with Maven
      run: mvn package
    - name: Save jar artifact
      uses: actions/upload-artifact@master
      with:
        name: s3server
        path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to the remote server
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: s3server
          path: target/*.jar
      - name: Deploy the package to the remote server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/*.jar
          remote: github/
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
